
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd

spec:
  project: default

  sources:
    # Official Helm chart.
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 91.8.1

      helm:
        releaseName: monitoring
        # CRDs already exist in-cluster; avoid client-side annotation limits.
        skipCrds: true
        valueFiles:
          - $values/helm/monitoring/values.yaml

    # Custom configuration stored in GitHub.
    - repoURL: https://github.com/hoang4325/Openstack-Cloud-Native-Private.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
