[k8s_control]
k8s-control-01 ansible_host=172.30.0.114 node_ip=10.20.0.10

[k8s_workers]
k8s-worker-01 ansible_host=172.30.0.112 node_ip=10.20.0.11
k8s-monitoring-01 ansible_host=172.30.0.105 node_ip=10.20.0.12

[k8s_cluster:children]
k8s_control
k8s_workers

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
