
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: demo
spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-web

  template:
    metadata:
      labels:
        app: demo-web

    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01

      containers:
        - name: whoami
          image: traefik/whoami:v1.11.0

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: demo
spec:
  type: ClusterIP

  selector:
    app: demo-web

  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-web
  namespace: demo

spec:
  ingressClassName: traefik

  rules:
    - host: demo.lab.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-web
                port:
                  number: 80
